[package]
name = "batteread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bluetooth-serial-port-async = { version = "*", git = "https://github.com/felixwatts/bluetooth-serial-port-async.git", features = ["tokio"], default-features = false }
tokio = { version = "1", features = ["full"] }
tokio-modbus = { version = "*", default-features = false, features = ["rtu"] }
uuid = "*"
futures-util = "*"
crc16 = "0.4.0"
hex = "*"
bluer = { version = "0.17.3", features = ["full"] }
anyhow = "1.0.89"

[dev-dependencies]


