[package]
name = "batteread"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# mio = { version = "0.8", features = ["os-poll", "os-ext"] }
# bluetooth-serial-port = "0.5.1"
btleplug = "0.9.0"
tokio = { version = "1", features = ["full"] }
tokio-modbus = "0.5"

